# Generated by Django 2.2.9 on 2020-07-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
