# Generated by Django 2.2.9 on 2020-07-31 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0005_answer_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
