# Generated by Django 2.2.9 on 2020-07-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_auto_20200731_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='owner',
            new_name='user',
        ),
    ]
